services:
  db:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '${PL_DB_PORT:-5432}:5432'

volumes:
  db_data:
